# Use a modern version of the Docker Compose file format.
version: '3.8'

# Define the services that make up your application.
services:
  # The Express.js application service.
  node-app:
    # Build the image from the Dockerfile in the current directory.
    build: .
    # Map port 3000 on the host to port 3000 in the container.
    ports:
      - "3000:3000"
    # Restart the container if it fails.
    restart: always
    # Ensure the database is running before starting the Node.js app.
    depends_on:
      - db
    # Set environment variables for the Node.js application to connect to the database.
    environment:
      # The database host is the name of the MySQL service.
      DB_HOST: db
      # The user and password for the application to connect to the database.
      DB_USER: remit
      DB_PASSWORD: password
      DB_DATABASE: remittance

  # The MySQL database service.
  db:
    # Use a specific version of the MySQL image for stability.
    image: mysql:8.0
    # Restart the container if it fails.
    restart: always
    # Set environment variables to configure the MySQL database.
    environment:
      # This is the password for the 'root' user.
      MYSQL_ROOT_PASSWORD: password
      # This is the database that will be created on startup.
      MYSQL_DATABASE: remittance
      # This is a new user that will be created.
      MYSQL_USER: remit
      # This is the password for the new user.
      MYSQL_PASSWORD: password
    # Map the internal data volume to a named volume for persistence.
    volumes:
      - db_data:/var/lib/mysql
    # Expose the database port to the host for local access (optional, but useful).
    ports:
      - "3308:3306"

  # The phpMyAdmin service for database management.
  phpmyadmin:
    # Use the official phpMyAdmin image.
    image: phpmyadmin/phpmyadmin
    # Restart the container if it fails.
    restart: always
    # Ensure the database is running before starting phpMyAdmin.
    depends_on:
      - db
    # Map port 8080 on the host to port 80 in the container.
    ports:
      - "8080:80"
    # Configure phpMyAdmin to connect to the MySQL service.
    environment:
      # The database host is the name of the MySQL service.
      PMA_HOST: db
      # The port for the database.
      PMA_PORT: 3308
      # Set this to 1 to allow connecting to any MySQL host on the login page.
      PMA_ARBITRARY: 1
      # Use the same root password as the MySQL service for login convenience.
      MYSQL_ROOT_PASSWORD: password

# Define the named volume for persistent database storage.
volumes:
  db_data:
